QUESTIONS = [
{"image": "images/item/Allow_Throw.png", "answer": "allow throw"},
{"image": "images/item/Antique_Cuirass.png", "answer": "antique cuirass"},
{"image": "images/item/Arcane_Boots.png", "answer": "arcane boots"},
{"image": "images/item/Ares_Belt.png", "answer": "ares belt"},
{"image": "images/item/Athena's_Shield.png", "answer": "athena's shield"},
{"image": "images/item/Azure_Blade.png", "answer": "azure blade"},
{"image": "images/item/Berserker_Fury.png", "answer": "berserker fury"},
{"image": "images/item/Black_Ice_Shield.png", "answer": "black ice shield"},
{"image": "images/item/Blade_Armor.png", "answer": "blade armor"},
{"image": "images/item/Blade_of_Despair.png", "answer": "blade of despair"},
{"image": "images/item/Blade_of_the_Heptaseas.png", "answer": "blade of the heptaseas"},
{"image": "images/item/Bloody_Retribution.png", "answer": "bloody retribution"},
{"image": "images/item/Book_of_Sages.png", "answer": "book of sages"},
{"image": "images/item/Boots.png", "answer": "boots"},
{"image": "images/item/Broken_Heart.png", "answer": "broken heart"},
{"image": "images/item/Brute_Force_Breastplate.png", "answer": "brute force breastplate"},
{"image": "images/item/Chastise_Pauldron.png", "answer": "chastise pauldron"},
{"image": "images/item/Clock_of_Destiny.png", "answer": "clock of destiny"},
{"image": "images/item/Conceal.png", "answer": "conceal"},
{"image": "images/item/Concentrated_Energy.png", "answer": "concentrated energy"},
{"image": "images/item/Corrosion_Scythe.png", "answer": "corrosion scythe"},
{"image": "images/item/Cursed_Helmet.png", "answer": "cursed helmet"},
{"image": "images/item/Dagger.png", "answer": "dagger"},
{"image": "images/item/Demon_Hunter_Sword.png", "answer": "demon hunter sword"},
{"image": "images/item/Demon_Shoes.png", "answer": "demon shoes"},
{"image": "images/item/Dire_Hit.png", "answer": "dire hit"},
{"image": "images/item/Divine_Glaive.png", "answer": "divine glaive"},
{"image": "images/item/Dominance_Ice.png", "answer": "dominance ice"},
{"image": "images/item/Dreadnaught_Armor.png", "answer": "dreadnaught armor"},
{"image": "images/item/Elegant_Gem.png", "answer": "elegant gem"},
{"image": "images/item/Enchanted_Talisman.png", "answer": "enchanted talisman"},
{"image": "images/item/Encourage.png", "answer": "encourage"},
{"image": "images/item/Endless_Battle_.png", "answer": "endless battle"},
{"image": "images/item/Exotic_Veil.png", "answer": "exotic veil"},
{"image": "images/item/Expert_Gloves.png", "answer": "expert gloves"},
{"image": "images/item/Favor.png", "answer": "favor"},
{"image": "images/item/Feather_of_Heaven.png", "answer": "feather of heaven"},
{"image": "images/item/Flame_Retribution.png", "answer": "flame retribution"},
{"image": "images/item/Flask_of_the_Oasis.png", "answer": "flask of the oasis"},
{"image": "images/item/Fleeting_Time.png", "answer": "fleeting time"},
{"image": "images/item/Flower_of_Hope.png", "answer": "flower of hope"},
{"image": "images/item/Fury_Hammer.png", "answer": "fury hammer"},
{"image": "images/item/Genius_Wand.png", "answer": "genius wand"},
{"image": "images/item/Glowing_Wand.png", "answer": "glowing wand"},
{"image": "images/item/Golden_Staff.png", "answer": "golden staff"},
{"image": "images/item/Great_Dragon_Spear.png", "answer": "great dragon spear"},
{"image": "images/item/Guardian_Helmet.png", "answer": "guardian helmet"},
{"image": "images/item/Haas_Claws.png", "answer": "haas claws"},
{"image": "images/item/Healing_Necklace.png", "answer": "healing necklace"},
{"image": "images/item/Hero_Ring.png", "answer": "hero ring"},
{"image": "images/item/Holy_Crystal.png", "answer": "holy crystal"},
{"image": "images/item/Hunter_Strike.png", "answer": "hunter strike"},
{"image": "images/item/Ice_Queen_Wand.png", "answer": "ice queen wand"},
{"image": "images/item/Ice_Retribution.png", "answer": "ice retribution"},
{"image": "images/item/Immortality.png", "answer": "immortality"},
{"image": "images/item/Iron_Hunting_Bow.png", "answer": "iron hunting bow"},
{"image": "images/item/Javelin.png", "answer": "javelin"},
{"image": "images/item/Knife.png", "answer": "knife"},
{"image": "images/item/Lantern_of_Hope.png", "answer": "lantern of hope"},
{"image": "images/item/Leather_Jerkin.png", "answer": "leather jerkin"},
{"image": "images/item/Legion_Sword.png", "answer": "legion sword"},
{"image": "images/item/Lightning_Truncheon.png", "answer": "lightning truncheon"},
{"image": "images/item/Magic_Blade.png", "answer": "magic blade"},
{"image": "images/item/Magic_Necklace.png", "answer": "magic necklace"},
{"image": "images/item/Magic_Potion.png", "answer": "magic potion"},
{"image": "images/item/Magic_Resist_Cloak.png", "answer": "magic resist cloak"},
{"image": "images/item/Magic_Shoes.png", "answer": "magic shoes"},
{"image": "images/item/Magic_Wand.png", "answer": "magic wand"},
{"image": "images/item/Malefic_Gun.png", "answer": "malefic gun"},
{"image": "images/item/Malefic_Roar.png", "answer": "malefic roar"},
{"image": "images/item/Molten_Essence.png", "answer": "molten essence"},
{"image": "images/item/Mystery_Codex.png", "answer": "mystery codex"},
{"image": "images/item/Mystic_Container.png", "answer": "mystic container"},
{"image": "images/item/Ogre_Tomahawk.png", "answer": "ogre tomahawk"},
{"image": "images/item/Oracle.png", "answer": "oracle"},
{"image": "images/item/Power_Crystal.png", "answer": "power crystal"},
{"image": "images/item/Power_Potion.png", "answer": "power potion"},
{"image": "images/item/Queen_Wings.png", "answer": "queen wings"},
{"image": "images/item/Radiant_Armor.png", "answer": "radiant armor"},
{"image": "images/item/Rapid_Boots.png", "answer": "rapid boots"},
{"image": "images/item/Regular_Spear.png", "answer": "regular spear"},
{"image": "images/item/Rock_Potion.png", "answer": "rock potion"},
{"image": "images/item/Rogue_Meteor.png", "answer": "rogue meteor"},
{"image": "images/item/Rose_Gold_Meteor.png", "answer": "rose gold meteor"},
{"image": "images/item/Sea_Halberd.png", "answer": "sea halberd"},
{"image": "images/item/Silence_Robe.png", "answer": "silence robe"},
{"image": "images/item/Sky_Piercer.png", "answer": "sky piercer"},
{"image": "images/item/Starlium_Scythe.png", "answer": "starlium scythe"},
{"image": "images/item/Swift_Boots.png", "answer": "swift boots"},
{"image": "images/item/Swift_Crossbow.png", "answer": "swift crossbow"},
{"image": "images/item/Throw_Forbidden.png", "answer": "throw forbidden"},
{"image": "images/item/Thunder_Belt.png", "answer": "thunder belt"},
{"image": "images/item/Tome_of_Evil.png", "answer": "tome of evil"},
{"image": "images/item/Tough_Boots.png", "answer": "tough boots"},
{"image": "images/item/Vampire_Mallet.png", "answer": "vampire mallet"},
{"image": "images/item/Vitality_Crystal.png", "answer": "vitality crystal"},
{"image": "images/item/War_Axe.png", "answer": "war axe"},
{"image": "images/item/Warrior_Boots.png", "answer": "warrior boots"},
{"image": "images/item/Wind_of_Nature.png", "answer": "wind of nature"},
{"image": "images/item/Windtalker.png", "answer": "windtalker"},
{"image": "images/item/Winter_Crown.png", "answer": "winter crown"},
{"image": "images/item/Wishing_Lantern.png", "answer": "wishing lantern"}
]
