QUESTIONS = [
{"image": "images/item/Allow_Throw.png", "answer": "allow throw", "aliases": []},
{"image": "images/item/Antique_Cuirass.png", "answer": "antique cuirass", "aliases": ["anti cuirass"]},
{"image": "images/item/Arcane_Boots.png", "answer": "arcane boots", "aliases": ["sepatu magic"]},
{"image": "images/item/Ares_Belt.png", "answer": "ares belt", "aliases": []},
{"image": "images/item/Athena's_Shield.png", "answer": "athena shield", "aliases": []},
{"image": "images/item/Azure_Blade.png", "answer": "azure blade", "aliases": []},
{"image": "images/item/Berserker_Fury.png", "answer": "berserker fury", "aliases": ["tamako"]},
{"image": "images/item/Black_Ice_Shield.png", "answer": "black ice shield", "aliases": []},
{"image": "images/item/Blade_Armor.png", "answer": "blade armor", "aliases": ["bm"]},
{"image": "images/item/Blade_of_Despair.png", "answer": "blade of despair", "aliases": ["bod"]},
{"image": "images/item/Blade_of_the_Heptaseas.png", "answer": "blade of heptaseas", "aliases": ["heptaseas"]},
{"image": "images/item/Bloody_Retribution.png", "answer": "bloody retribution", "aliases": ["retri ungu"]},
{"image": "images/item/Book_of_Sages.png", "answer": "book of sages", "aliases": []},
{"image": "images/item/Boots.png", "answer": "boots", "aliases": ["sepatu"]},
{"image": "images/item/Broken_Heart.png", "answer": "broken heart", "aliases": ["pasif carmilla"]},
{"image": "images/item/Brute_Force_Breastplate.png", "answer": "brute force breastplate", "aliases": ["brute force"]},
{"image": "images/item/Chastise_Pauldron.png", "answer": "chastise pauldron", "aliases": ["chastise"]},
{"image": "images/item/Clock_of_Destiny.png", "answer": "clock of destiny", "aliases": ["cod"]},
{"image": "images/item/Conceal.png", "answer": "conceal", "aliases": []},
{"image": "images/item/Concentrated_Energy.png", "answer": "concentrated energy", "aliases": ["concentrated"]},
{"image": "images/item/Corrosion_Scythe.png", "answer": "corrosion scythe", "aliases": ["corrosion"]},
{"image": "images/item/Cursed_Helmet.png", "answer": "cursed helmet", "aliases": []},
{"image": "images/item/Dagger.png", "answer": "dagger", "aliases": []},
{"image": "images/item/Demon_Hunter_Sword.png", "answer": "demon hunter sword", "aliases": ["dhs"]},
{"image": "images/item/Demon_Shoes.png", "answer": "demon shoes", "aliases": ["sepatu mana"]},
{"image": "images/item/Dire_Hit.png", "answer": "dire hit", "aliases": ["roam biru"]},
{"image": "images/item/Divine_Glaive.png", "answer": "divine glaive", "aliases": ["glaive"]},
{"image": "images/item/Dominance_Ice.png", "answer": "dominance ice", "aliases": ["dominance"]},
{"image": "images/item/Dreadnaught_Armor.png", "answer": "dreadnaught armor", "aliases": ["armor putih"]},
{"image": "images/item/Elegant_Gem.png", "answer": "elegant gem", "aliases": []},
{"image": "images/item/Enchanted_Talisman.png", "answer": "enchanted talisman", "aliases": ["buku mana"]},
{"image": "images/item/Encourage.png", "answer": "encourage", "aliases": ["roam merah"]},
{"image": "images/item/Endless_Battle_.png", "answer": "endless battle", "aliases": []},
{"image": "images/item/Exotic_Veil.png", "answer": "exotic veil", "aliases": []},
{"image": "images/item/Expert_Gloves.png", "answer": "expert gloves", "aliases": ["mentahan skypiercer"]},
{"image": "images/item/Favor.png", "answer": "favor", "aliases": []},
{"image": "images/item/Feather_of_Heaven.png", "answer": "feather of heaven", "aliases": []},
{"image": "images/item/Flame_Retribution.png", "answer": "flame retribution", "aliases": ["retri merah"]},
{"image": "images/item/Flask_of_the_Oasis.png", "answer": "flask of oasis", "aliases": ["foto"]},
{"image": "images/item/Fleeting_Time.png", "answer": "fleeting time", "aliases": []},
{"image": "images/item/Flower_of_Hope.png", "answer": "flower of hope", "aliases": ["pasif floryn"]},
{"image": "images/item/Fury_Hammer.png", "answer": "fury hammer", "aliases": []},
{"image": "images/item/Genius_Wand.png", "answer": "genius wand", "aliases": []},
{"image": "images/item/Glowing_Wand.png", "answer": "glowing wand", "aliases": []},
{"image": "images/item/Golden_Staff.png", "answer": "golden staff", "aliases": []},
{"image": "images/item/Great_Dragon_Spear.png", "answer": "great dragon spear", "aliases": []},
{"image": "images/item/Guardian_Helmet.png", "answer": "guardian helmet", "aliases": []},
{"image": "images/item/Haas_Claws.png", "answer": "haas claws", "aliases": []},
{"image": "images/item/Healing_Necklace.png", "answer": "healing necklace", "aliases": ["mentahan guardian helmet"]},
{"image": "images/item/Hero_Ring.png", "answer": "hero ring", "aliases": ["mentahan oracle"]},
{"image": "images/item/Holy_Crystal.png", "answer": "holy crystal", "aliases": []},
{"image": "images/item/Hunter_Strike.png", "answer": "hunter strike", "aliases": []},
{"image": "images/item/Ice_Queen_Wand.png", "answer": "ice queen wand", "aliases": []},
{"image": "images/item/Ice_Retribution.png", "answer": "ice retribution", "aliases": []},
{"image": "images/item/Immortality.png", "answer": "immortality", "aliases": []},
{"image": "images/item/Iron_Hunting_Bow.png", "answer": "iron hunting bow", "aliases": []},
{"image": "images/item/Javelin.png", "answer": "javelin", "aliases": []},
{"image": "images/item/Knife.png", "answer": "knife", "aliases": ["pisau"]},
{"image": "images/item/Lantern_of_Hope.png", "answer": "lantern of hope", "aliases": []},
{"image": "images/item/Leather_Jerkin.png", "answer": "leather jerkin", "aliases": ["armor"]},
{"image": "images/item/Legion_Sword.png", "answer": "legion sword", "aliases": []},
{"image": "images/item/Lightning_Truncheon.png", "answer": "lightning truncheon", "aliases": ["truncheon"]},
{"image": "images/item/Magic_Blade.png", "answer": "magic blade", "aliases": []},
{"image": "images/item/Magic_Necklace.png", "answer": "magic necklace", "aliases": []},
{"image": "images/item/Magic_Potion.png", "answer": "magic potion", "aliases": []},
{"image": "images/item/Magic_Resist_Cloak.png", "answer": "magic resist cloak", "aliases": ["magic resist"]},
{"image": "images/item/Magic_Shoes.png", "answer": "magic shoes", "aliases": ["sepatu cooldown"]},
{"image": "images/item/Magic_Wand.png", "answer": "magic wand", "aliases": []},
{"image": "images/item/Malefic_Gun.png", "answer": "malefic gun", "aliases": []},
{"image": "images/item/Malefic_Roar.png", "answer": "malefic roar", "aliases": ["pistol"]},
{"image": "images/item/Molten_Essence.png", "answer": "molten essence", "aliases": ["molten"]},
{"image": "images/item/Mystery_Codex.png", "answer": "mystery codex", "aliases": []},
{"image": "images/item/Mystic_Container.png", "answer": "mystic container", "aliases": []},
{"image": "images/item/Ogre_Tomahawk.png", "answer": "ogre tomahawk", "aliases": []},
{"image": "images/item/Oracle.png", "answer": "oracle", "aliases": []},
{"image": "images/item/Power_Crystal.png", "answer": "power crystal", "aliases": []},
{"image": "images/item/Power_Potion.png", "answer": "power potion", "aliases": []},
{"image": "images/item/Queen_Wings.png", "answer": "queen wings", "aliases": []},
{"image": "images/item/Radiant_Armor.png", "answer": "radiant armor", "aliases": []},
{"image": "images/item/Rapid_Boots.png", "answer": "rapid boots", "aliases": []},
{"image": "images/item/Regular_Spear.png", "answer": "regular spear", "aliases": []},
{"image": "images/item/Rock_Potion.png", "answer": "rock potion", "aliases": []},
{"image": "images/item/Rogue_Meteor.png", "answer": "rogue meteor", "aliases": []},
{"image": "images/item/Rose_Gold_Meteor.png", "answer": "rose gold meteor", "aliases": ["rose gold"]},
{"image": "images/item/Sea_Halberd.png", "answer": "sea halberd", "aliases": []},
{"image": "images/item/Silence_Robe.png", "answer": "silence robe", "aliases": []},
{"image": "images/item/Sky_Piercer.png", "answer": "sky piercer", "aliases": []},
{"image": "images/item/Starlium_Scythe.png", "answer": "starlium scythe", "aliases": ["starlium"]},
{"image": "images/item/Swift_Boots.png", "answer": "swift boots", "aliases": []},
{"image": "images/item/Swift_Crossbow.png", "answer": "swift crossbow", "aliases": []},
{"image": "images/item/Throw_Forbidden.png", "answer": "throw forbidden", "aliases": ["anti jawhead"]},
{"image": "images/item/Thunder_Belt.png", "answer": "thunder belt", "aliases": []},
{"image": "images/item/Tome_of_Evil.png", "answer": "tome of evil", "aliases": []},
{"image": "images/item/Tough_Boots.png", "answer": "tough boots", "aliases": []},
{"image": "images/item/Vampire_Mallet.png", "answer": "vampire mallet", "aliases": []},
{"image": "images/item/Vitality_Crystal.png", "answer": "vitality crystal", "aliases": []},
{"image": "images/item/War_Axe.png", "answer": "war axe", "aliases": []},
{"image": "images/item/Warrior_Boots.png", "answer": "warrior boots", "aliases": []},
{"image": "images/item/Wind_of_Nature.png", "answer": "wind of nature", "aliases": ["won"]},
{"image": "images/item/Windtalker.png", "answer": "windtalker", "aliases": []},
{"image": "images/item/Winter_Crown.png", "answer": "winter crown", "aliases": ["winter"]},
{"image": "images/item/Wishing_Lantern.png", "answer": "wishing lantern", "aliases": []}
]
